
export const traffic = [
    {
        dataId: '0001',
        driverName : 'John Bryan Delda',
        vehicleName : 'Porsche',
        plateNumber: 'VSX09881',
        entranceTime: '13:41',
        exitTime: '14:30',
        date : '11/14/20',
        driverId: '29612150',
        type: 'Student',
        School: 'School of Engineering, Architecture, and Information Technology',
        Field: 'BS Computer Engineering',
        classYear: '5',
    },
    {
        dataId: '0002',
        driverName : 'John Bryan Delda',
        vehicleName : 'Porsche',
        plateNumber: 'VSX09881',
        entranceTime: '13:41',
        exitTime: '14:30',
        date : '11/15/20',
        driverId: '29612150',
        type: 'Student',
        School: 'School of Engineering, Architecture, and Information Technology',
        Field: 'BS Computer Engineering',
        classYear: '5',
    },
    {
        dataId: '0002',
        driverName : 'John Bryan Delda',
        vehicleName : 'Porsche',
        plateNumber: 'VSX09881',
        entranceTime: '13:41',
        exitTime: '14:30',
        date : '11/14/20',
        driverId: '29612150',
        type: 'Student',
        School: 'School of Engineering, Architecture, and Information Technology',
        Field: 'BS Computer Engineering',
        classYear: '5',
    },
    {
        dataId: '0003',
        driverName : 'John Bryan Delda',
        vehicleName : 'Porsche',
        plateNumber: 'VSX09881',
        entranceTime: '13:41',
        exitTime: '14:30',
        date : '11/14/20',
        driverId: '29612150',
        type: 'Student',
        School: 'School of Engineering, Architecture, and Information Technology',
        Field: 'BS Computer Engineering',
        classYear: '5',
    },
    {
        dataId: '0004',
        driverName : 'John Bryan Delda',
        vehicleName : 'Porsche',
        plateNumber: 'VSX09881',
        entranceTime: '13:41',
        exitTime: '14:30',
        date : '11/14/20',
        driverId: '29612150',
        type: 'Student',
        School: 'School of Engineering, Architecture, and Information Technology',
        Field: 'BS Computer Engineering',
        classYear: '5',
    },
    {
        dataId: '0005',
        driverName : 'John Bryan Delda',
        vehicleName : 'Porsche',
        plateNumber: 'VSX09881',
        entranceTime: '13:41',
        exitTime: '14:30',
        date : '11/14/20',
        driverId: '29612150',
        type: 'Student',
        School: 'School of Engineering, Architecture, and Information Technology',
        Field: 'BS Computer Engineering',
        classYear: '5',
    },
    {
        dataId: '0006',
        driverName : 'John Bryan Delda',
        vehicleName : 'Porsche',
        plateNumber: 'VSX09881',
        entranceTime: '13:41',
        exitTime: '14:30',
        date : '11/14/20',
        driverId: '29612150',
        type: 'Student',
        School: 'School of Engineering, Architecture, and Information Technology',
        Field: 'BS Computer Engineering',
        classYear: '5',
    },
    {
        dataId: '0007',
        driverName : 'John Bryan Delda',
        vehicleName : 'Porsche',
        plateNumber: 'VSX09881',
        entranceTime: '13:41',
        exitTime: '14:30',
        date : '11/14/20',
        driverId: '29612150',
        type: 'Student',
        School: 'School of Engineering, Architecture, and Information Technology',
        Field: 'BS Computer Engineering',
        classYear: '5',
    },
    {
        dataId: '0007',
        driverName : 'John Bryan Delda',
        vehicleName : 'Porsche',
        plateNumber: 'VSX09881',
        entranceTime: '13:41',
        exitTime: '14:30',
        date : '11/14/20',
        driverId: '29612150',
        type: 'Student',
        School: 'School of Engineering, Architecture, and Information Technology',
        Field: 'BS Computer Engineering',
        classYear: '5',
    },
]